### ISSUE TITLE
validate required used fields before trying to build MangoPayUser

### ISSUE THREAD

**Issue by flaviamissi** [FundedByMe/django-mangopay#56]
I know it's a corner case, but when a user doesn't have all the required fields to be sent to mangopay api it gives a very unhelpful error, something like `Response Exception - No exception supplied`. I got this creating an user via command line and then trying to perform a lend to a campaign. After some digging I found that the problem was my user was missing both first and last_name, fields.

**Comment by anah** [comment]
This is something that needs to be in https://github.com/MangoPay/mangopay2-python-sdk

**Comment by flaviamissi** [comment]
Fair enough! I created a similar issue on their repository: https://github.com/MangoPay/mangopay2-python-sdk/issues/25
